//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooBdEntities1 : DbContext
    {
        private static ZooBdEntities1 _context;
        public ZooBdEntities1()
            : base("name=ZooBdEntities1")
        {
        }
        public static ZooBdEntities1 GetContext()
        {
            if (_context == null)
                _context = new ZooBdEntities1();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<DetailsOrder> DetailsOrder { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Povider> Povider { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeAnimals> TypeAnimals { get; set; }
        public virtual DbSet<Category> Category { get; set; }
    }
}
