//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DetailsOrder = new HashSet<DetailsOrder>();
        }
    
        public int Id_Prod { get; set; }
        public string NameProduct { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> PriceProd { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_TypeAnim { get; set; }
        public Nullable<int> Id_Provid { get; set; }
        public string PhotoProduct { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsOrder> DetailsOrder { get; set; }
        public virtual Povider Povider { get; set; }
        public virtual TypeAnimals TypeAnimals { get; set; }
    }
}
